image: continuumio/miniconda:4.7.10

before_script:
  - python --version
  - conda env create -f environment.yml --name test 
  - conda init bash
  - source ~/.bashrc 
  - conda activate test 
  - conda install pytest pytest-cov


stages:
  - Test


doctest:
  stage: Test
  script:
    - python -m doctest README.md


#pylint:
#  stage: Static Analysis
#  allow_failure: true
#  script:
#  - pylint -d C0301 power_system_split/*.py

testing:
  stage: Test
  script:
    - python -m pytest --cov=power_system_split tests/

