
configfile: "configs/config.sclopf.yaml"
configfile: "configs/config.yaml"

import numpy as np
import os

group_size = int(config["groupsize"])
temp_resolution = int(config["clustering"]["temporal"]["resolution_elec"].split("H")[0])

N_ITER = str(int(np.ceil(8760 / temp_resolution / group_size))-1)
NCLUSTERS = str(config["scenario"]["clusters"][0])

path_syntax = config["path_syntax"]

if path_syntax == 'new':
    # added by Jan
    try:
        s_max_pu = config["lines"]["s_max_pu"]
    except:
        s_max_pu = "0.7"
        
    s_max_pu_path = f"s_max_pu_{s_max_pu}/" if s_max_pu != "" else "" 

    
elif path_syntax == 'old':
    s_max_pu_path = ''
    
    
co2_relaxation = config['co2_relaxation']
co2_relaxation_path = f"co2_rel_{co2_relaxation}/" if co2_relaxation else ""

print(co2_relaxation_path + s_max_pu_path)
path =  co2_relaxation_path + s_max_pu_path 
os.makedirs(path, exist_ok=True)

rule prepare_sclopf:
    input:
        network = "submodules/pypsa-eur/" + s_max_pu_path + "results/networks/elec_s_" + NCLUSTERS + "_ec_lv1.0_{opts}.nc",
        lookup = "data/np_lookup.csv"
    output: f"{path}prenetworks/elec_s_" + NCLUSTERS + "_ec_lv1.0_{opts}_prepared.nc"
    resources: mem=4000
    threads: 4
    script: "scripts/prepare_sclopf.py"


rule solve_sclopf:
    input: 
        prepared = path + "prenetworks/elec_s_" + NCLUSTERS + "_ec_lv1.0_{opts}_prepared.nc",
        previous = lambda w: path + f"postnetworks/{w.opts}/sclopf-elec_s_" + NCLUSTERS + f"_ec_lv1.0-{int(w.i)-1}.nc" if int(w.i) > 0 else []
    output: path + "postnetworks/{opts}/sclopf-elec_s_" + NCLUSTERS + "_ec_lv1.0-{i}.nc"
    resources: mem_mb=100000
    threads: 4
    script: "scripts/solve_sclopf.py"


rule reassemble_all:
    input:
        pre = path + "prenetworks/elec_s_" + NCLUSTERS + "_ec_lv1.0_{opts}_prepared.nc",
        sub = path + "postnetworks/{opts}/sclopf-elec_s_" + NCLUSTERS + "_ec_lv1.0-" + N_ITER + ".nc"
    output: path + "postnetworks/sclopf-elec_s_" + NCLUSTERS + "_ec_lv1.0_{opts}.nc"
    script: "scripts/reassemble.py"


rule run_all:
    input:
        expand(
            path + "postnetworks/Co2L{Co2L}/sclopf-elec_s_" + NCLUSTERS + "_ec_lv1.0-{i}.nc",
            Co2L = config["Co2-scenarios"],
            i = [n for n in range(int(np.ceil(8760 / temp_resolution / group_size)))],
            onerror=lambda e: print(f"Warning: {e} failed, continuing..."),
        )
        

