#!/usr/bin/python3
# -*- coding: utf-8 -*

"""Run cascade experiments by introducing line failures
to the optimal power systems generated by PyPSA."""

import pickle
import gzip
import sys
import networkx as nx
from tqdm import tqdm

sys.path.append('./') 
from utils import cascade_simulation, data_handling

# Send messages to mattermost
import utils.config as cfg
from utils import send_mattermost_messages

# Setup paths to solved PyPSA networks and results of this script
path_to_pypsa_network_lopf = './data/European_networks_lopf/'
path_to_pypsa_network_sclopf = './data/European_networks_sclopf/'
save_path_sclopf =  './results/sclopf/cascade_results/'
save_path_lopf =  './results/lopf/cascade_results/'

# Dummy decorator to not get stuck on @profile
if 'profile' not in globals():
    def profile(func):
        return func
    
    
def run_cascade_single_line_failures(co2l: float, n_nodes: int,
                                     save_all_cascades: bool = False, snet_index: int = 0,
                                     use_sclopf: bool = False):
    """_summary_

    Args:
        co2l (float): _description_
        n_nodes (int): _description_
        save_all_cascades (bool, optional): _description_. Defaults to False.
        snet_index (int, optional): _description_. Defaults to 0.
        use_sclopf (bool): If 'True' use num_parallel lookup table for non sclopf PyPSA network and load this data set. Defaults to False.
    """
    
    # Load PyPSA network, the graph of the subnetwork and its matrices
    if use_sclopf:
        path_to_pypsa_network = path_to_pypsa_network_sclopf
        full_path_to_file = path_to_pypsa_network + f'sclopf-elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l:.1f}-2920SEG.nc'
    else:
        path_to_pypsa_network = path_to_pypsa_network_lopf
        full_path_to_file = path_to_pypsa_network + f'elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-3H.nc'
        
    network = data_handling.load_pypsa_network(full_path_to_file, use_sclopf)
    nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)
    I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(nx_graph)
    
    # Calculate possible N-1 failures (using non-bridges)
    bridge_idxs = data_handling.nx_edges_to_matrix_indices(nx.bridges(nx_graph),
                                                           nx_graph)
    n_1_failures = cascade_simulation.calc_possible_single_line_failures(num_parallels, ignored_idxs=bridge_idxs)
    
    splitting_cascades = dict()
    
    for ii_snap, snapshot in enumerate(tqdm(network.snapshots)):
        key_now = snapshot.strftime('%Y-%m-%d %H:00')
        P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)
        
        res_dict = dict()
        for initial_failure in n_1_failures:
            
            failing_links, system_split = cascade_simulation.simulate_cascade(I_m, B_d, P_0, line_limits,
                                                                            num_parallels, initial_failure,
                                                                            max_cascade_length=1, use_sclopf=use_sclopf)
            if use_sclopf and len(failing_links) > 1:
                raise(RuntimeError('PyPSA networks are not N-1 stable!'))
            
            if save_all_cascades:
                res_dict[tuple(initial_failure)] = failing_links, system_split
                
            elif system_split:
                res_dict[tuple(initial_failure)] = failing_links
                
                
        splitting_cascades[key_now] = res_dict
        
    if use_sclopf:
        save_path = save_path_sclopf
    else:
        save_path = save_path_lopf
            
    fpath_out = save_path + f"system_splits_singlelinefailures_Co2L{co2l}_n{n_nodes}"
    
    if not use_sclopf:
        fpath_out += "_lopf"
    
    if save_all_cascades:
            fpath_out += "_allcascades"
            
    with gzip.open( fpath_out + ".pklz", 'wb') as handle:
        pickle.dump(splitting_cascades, handle, protocol = pickle.HIGHEST_PROTOCOL)
        
    if cfg.mattermost_url is not None:
        message_text = f"Cascade for single line failures simulations with N={n_nodes}, C02_lvl={co2l} finished and results saved in '" + fpath_out + "'."
        send_mattermost_messages.post_message(message_text, cfg.mattermost_url)
    
    return
    
    
@profile    
def run_cascade_dual_line_failures(co2l: float, n_nodes: int,
                save_all_cascades: bool = False, snet_index: int = 0,
                check_n1_security: bool = True, use_sclopf: bool = True):
    """Run cascade experiments by introducing dual line failures.

    Args:
        co2l (float): co2 level as float
        n_nodes (int): Number of nodes in PyPSA network.
        save_all_cascades (bool, optional): _description_. Defaults to False.
        snet_index (int, optional): Select a particular subnetwork for calculations (if the pypsa network has different ones). 
                For our data set, "0" indicates the Continental European AC grid. Defaults to 0.
        use_sclopf (bool): If 'True' use num_parallel lookup table for non sclopf PyPSA network and load this data set. Defaults to True.
    """
    
    if use_sclopf:
        path_to_pypsa_network = path_to_pypsa_network_sclopf
        full_path_to_file = path_to_pypsa_network + f'sclopf-elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l:.1f}-2920SEG.nc'
    else:
        path_to_pypsa_network = path_to_pypsa_network_lopf
        full_path_to_file = path_to_pypsa_network + f'elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-3H.nc'
        
    # Load PyPSA network, the graph of the subnetwork and its matrices
    network = data_handling.load_pypsa_network(full_path_to_file, use_sclopf)
    nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)
    I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(nx_graph)

    # Calculate possible N-1 and N-2 failures (using non-bridges)
    bridge_idxs = data_handling.nx_edges_to_matrix_indices(nx.bridges(nx_graph),
                                                            nx_graph)
    n_2_failures = cascade_simulation.calc_possible_double_line_failures(num_parallels, ignored_idxs=bridge_idxs,
                                                                         use_sclopf=use_sclopf)
    n_1_failures = cascade_simulation.calc_possible_single_line_failures(num_parallels, ignored_idxs=bridge_idxs)

    

    if check_n1_security:
    ### Check N-1 stability ###
        print('\n#### N-1 failures: Co2 level', co2l, ' | #Nodes:', n_nodes,' ####')
        for snapshot in tqdm(network.snapshots):

            P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

            for initial_failure in n_1_failures:

                failing_links, system_split = cascade_simulation.simulate_cascade(I_m, B_d, P_0, line_limits,
                                                                                num_parallels, initial_failure,
                                                                                max_cascade_length=1, use_sclopf=use_sclopf)
                if len(failing_links) > 1:
                    raise(RuntimeError('PyPSA networks are not N-1 stable!'))


    ### Simulation of N-2 failures ###
    print('\n#### N-2 failures: Co2 level', co2l, ' | #Nodes:', n_nodes, ' ####')
    splitting_cascades = dict()
    for idx_snap, snapshot in enumerate(tqdm(network.snapshots)):
        key_now = snapshot.strftime('%Y-%m-%d %H:00')
        #splitting_cascades[snapshot.strftime('%Y-%m-%d %H:00')] = {}

        P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

        res_dict = dict()
        for initial_failure in tqdm(n_2_failures, leave=False):
            
            failing_links, system_split = cascade_simulation.simulate_cascade(I_m, B_d, P_0, line_limits,
                                                                              num_parallels, initial_failure,
                                                                              use_sclopf=use_sclopf)
            
            
            if save_all_cascades:
                #splitting_cascades[snapshot.strftime('%Y-%m-%d %H:00')][tuple(initial_failure)] = failing_links
                res_dict[tuple(initial_failure)] = failing_links, system_split
            
            elif system_split:
                #splitting_cascades[snapshot.strftime('%Y-%m-%d %H:00')][tuple(initial_failure)] = failing_links 
                res_dict[tuple(initial_failure)] = failing_links
                
        splitting_cascades[key_now] = res_dict
        
    if use_sclopf:
        save_path = save_path_sclopf
    else:
        save_path = save_path_lopf
    
    if not use_sclopf:
        fpath_out += "_lopf"
        
    fpath_out = save_path + f"system_splits_Co2L{co2l}_n{n_nodes}"
    
    if save_all_cascades:
            fpath_out += "_allcascades"
            
    with gzip.open( fpath_out + ".pklz", 'wb') as handle:
        pickle.dump(splitting_cascades, handle, protocol = pickle.HIGHEST_PROTOCOL)

    if cfg.mattermost_url is not None:
        message_text = f"Cascade for single line failures simulations with N={n_nodes}, C02_lvl={co2l} finished and results saved in '" + fpath_out + "'."
        send_mattermost_messages.post_message(message_text, cfg.mattermost_url)
        
    return


if __name__ == '__main__':
    
    # Load arguments
    co2l_in = float(sys.argv[1]) 
    n_nodes_in = int(sys.argv[2])
    if len(sys.argv) > 3: 
        save_all_cascades_in = bool(sys.argv[3])
    else:
        save_all_cascades_in = False
    print("Starting dual line failures")
    run_cascade_dual_line_failures(co2l_in, n_nodes_in,
                                   save_all_cascades=save_all_cascades_in,
                                   use_sclopf=True,
                                   check_n1_security=False)
