#!/usr/bin/env python
# -*- coding: utf-8 -*

"""Run cascade experiments by introducing line failures
to the optimal power systems generated by PyPSA."""

import sys

sys.path.append("./")
from scripts.run_cascade_code import run_cascade_dual_line_failures
from utils.plot_mitigation_strategies import (
    data_line_mitigation_diff_nnlines,
    plot_bar_histograms_diff_nnlines,
)

# Load arguments
co2l_in = 0.1
n_nodes_in = 400

delta_paras = [1, 2, 5]
# n_lines_added = [547, 20, 10, 5, 1]
n_lines_added = [1, 5, 10, 20, 547]
# n_lines_added = [1]
for nn_lines in n_lines_added:
    for delta_num_parallel in delta_paras:
        print(
            f"Starting delta_num_parallel: {delta_num_parallel}, nn_links: {nn_lines}"
        )
        line_mitigation_dict = {
            "nn_links": nn_lines,
            "delta_num_parallel": delta_num_parallel,
            "extension_type": "most_likely_primary",
        }
        stop_timestamp_str = "2013-01-01 00:00"
        save_all_cascades_in = False
        print("Starting dual line failures")
        try:
            run_cascade_dual_line_failures(
                co2l_in,
                n_nodes_in,
                save_whole_cascades=save_all_cascades_in,
                use_sclopf=True,
                check_n1_security=True,
                line_mitigation_dict=line_mitigation_dict,
                stop_timestamp_str=stop_timestamp_str,
            )
            print(
                f"Finished delta_num_parallel: {delta_num_parallel}, nn_links: {nn_lines}"
            )
        except:
            print(
                f"delta_num_parallel: {delta_num_parallel}, nn_links: {nn_lines} failed"
            )

for delta_num_parallel in delta_paras:
    data_line_mitigation_diff_nnlines(
        delta_para=delta_num_parallel,
        save_res=True,
        n_lines_added=n_lines_added,
        stop_timestamp_str=stop_timestamp_str,
    )
plot_bar_histograms_diff_nnlines(delta_paras, save_fig=True, log_scale=False)


root_path = "../"  # This defaults to './', which should be the repository path
sys.path.append(root_path)

import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

import gzip
import pickle

import networkx as nx

from utils import data_handling
from utils.config import path_to_cascade_results_sclopf, path_to_pypsa_network_sclopf

snet_index = 0
network = data_handling.load_pypsa_network_from_path(
    path_to_pypsa_network_sclopf + "sclopf-elec_s_400_ec_lv1.0_Co2L0.1-2920SEG.nc", True
)
nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)
pos = nx.get_node_attributes(nx_graph, "pos")
I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(
    nx_graph
)

meta_data_path = path_to_cascade_results_sclopf
for delta_num_parallel in delta_paras:
    for nn_lines in n_lines_added:
        stop_timestamp_str = "2013-01-01 00:00"
        small_change_path = (
            meta_data_path
            + "system_splits_Co2L0.1_n400_"
            + f"lineextension_nnlines{nn_lines}"
            + f"_deltanumpara{delta_num_parallel:.4g}_"
            + f"stopped_{stop_timestamp_str}.pklz"
        )
        with gzip.open(small_change_path, "rb") as fh_in_r:
            _, vulnerable_edges_r, dict_r = pickle.load(fh_in_r)

        edge_number_to_nx_edge = {
            i: (u, v) for i, (u, v) in enumerate(nx_graph.edges())
        }
        nx_edge_to_edge_number = {
            (u, v): i for i, (u, v) in enumerate(nx_graph.edges())
        }
        # print([nx_edge_to_edge_number[edge] for edge in vulnerable_edges_r])
        vulnerable_edge_numbers = [
            nx_edge_to_edge_number[edge] for edge in vulnerable_edges_r
        ]

        trigger_pairs = list(dict_r["2013-01-01 00:00"].keys())
        unexpected_failure = False
        for trigger_pair in trigger_pairs:
            if len(set(trigger_pair).intersection(vulnerable_edge_numbers)) > 0:
                # print(trigger_pair, ": ", dict_r[stop_timestamp_str][trigger_pair])
                unexpected_failure = True
                break
        print(f"nn_lines={nn_lines}, delta_num_parallel={delta_num_parallel}: ")
        if unexpected_failure:
            print("extended line failure leads to cascade")
        else:
            print("extended line failure does not trigger any cascade")
