#!/usr/bin/env python
# -*- coding: utf-8 -*

"""Run cascade experiments by introducing line failures
to the optimal power systems generated by PyPSA."""

import gzip
import os
import pickle
import sys
from datetime import datetime as dt

import networkx as nx
import numpy as np
import pandas as pd
from tqdm import tqdm


sys.path.append("./")
# Send messages to mattermost
from utils.data_handling import get_co2_levels
import utils.config as cfg
from utils import (
    cascade_simulation,
    data_handling,
    # extend_transmission_capacity,
    send_mattermost_messages,
)
from utils.config import (
    path_to_cascade_results_sclopf,
    path_to_pypsa_network_sclopf,
    path_to_cascade_results_lopf
)

# Setup paths to solved PyPSA networks and results of this script
save_path_lopf = path_to_cascade_results_lopf
save_path_sclopf = path_to_cascade_results_sclopf

# Dummy decorator to not get stuck on @profile if not using profiling
if "profile" not in globals():

    def profile(func):
        return func


def run_cascade_single_line_failures(
    co2l: float,
    n_nodes: int,
    epsilon: float = 1e-4,
    save_whole_cascades: bool = True,
    snet_index: int = 0,
    use_sclopf: bool = False,
    initial_remove_all: bool = False,
):
    """Run the cascade simulation for single line failures.

    Args:
        co2l (float): CO2 level of the previously simulated PyPSA networks.
        n_nodes (int): Number of nodes fo the PyPSA networks.
        epsilon (float): Limit above smax needed for a line to fail. Default 1e-4.
        save_whole_cascades (bool, optional): If False, only the cascade trigger is saved. Defaults to True.
        snet_index (int, optional): _description_. Defaults to 0.
        use_sclopf (bool): If 'True' use num_parallel lookup table for non sclopf PyPSA network and load this data set. Defaults to False.
        initial_remove_all (bool): If 'True' remove all initial circuits and not use look_up_table.
    """

    # Load PyPSA network, the graph of the subnetwork and its matrices
    if use_sclopf:
        path_to_pypsa_network = path_to_pypsa_network_sclopf
        full_path_to_file = (
            path_to_pypsa_network
            + f"sclopf-elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-2920SEG.nc"
        )
    else:
        path_to_pypsa_network = path_to_pypsa_network_lopf
        full_path_to_file = (
            path_to_pypsa_network + f"elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-3H.nc"
        )

    network = data_handling.load_pypsa_network_from_path(full_path_to_file, use_sclopf)
    nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)
    I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(
        nx_graph
    )

    # Calculate possible N-1 failures (using non-bridges)
    bridge_idxs = data_handling.nx_edges_to_matrix_indices(
        nx.bridges(nx_graph), nx_graph
    )
    n_1_failures = cascade_simulation.calc_possible_single_line_failures(
        num_parallels, ignored_idxs=bridge_idxs
    )

    splitting_cascades = dict()

    for snapshot in tqdm(network.snapshots):
        key_now = snapshot.strftime("%Y-%m-%d %H:%M")
        P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

        res_dict = dict()
        for initial_failure in n_1_failures:

            failing_links, system_split = cascade_simulation.simulate_cascade(
                I_m,
                B_d,
                P_0,
                line_limits,
                num_parallels,
                initial_failure,
                use_sclopf=use_sclopf,
                epsilon=epsilon,
                initial_remove_all=initial_remove_all,
            )
            if use_sclopf and len(failing_links) > 1:
                raise RuntimeError("PyPSA networks are not N-1 stable!")

            if save_whole_cascades:
                res_dict[tuple(initial_failure)] = failing_links, system_split

            elif system_split:
                res_dict[tuple(initial_failure)] = failing_links

        splitting_cascades[key_now] = res_dict

    if use_sclopf:
        save_path = save_path_sclopf
    else:
        save_path = save_path_lopf
    os.makedirs(save_path, exist_ok=True)

    fpath_out = save_path + f"system_splits_singlelinefailures_Co2L{co2l}_n{n_nodes}"

    if abs(epsilon - 1e-4) > 1e-8:
        fpath_out += f"_epsilon{epsilon:.4e}"

    if not use_sclopf:
        fpath_out += "_lopf"

    if save_whole_cascades:
        fpath_out += "_allcascades"

    if initial_remove_all:
        fpath_out += "_allinitialcircuits"

    with gzip.open(fpath_out + ".pklz", "wb") as handle:
        pickle.dump(splitting_cascades, handle, protocol=pickle.HIGHEST_PROTOCOL)

    if cfg.mattermost_url is not None:
        message_text = (
            "Cascade for single line failures simulations (details in filename)"
            + f"with N={n_nodes}, C02_lvl={co2l} finished and results saved in '"
            + fpath_out
            + "'."
        )
        send_mattermost_messages.post_message(message_text, cfg.mattermost_url)

    return


@profile
def run_cascade_dual_line_failures(
    co2l: float,
    n_nodes: int,
    save_non_split_cascades: bool = True,
    snet_index: int = 0,
    check_n1_security: bool = True,
    use_sclopf: bool = True,
    line_mitigation_dict: dict = None,
    stop_timestamp_str: str = None,
    start_timestamp_str: str = None,
    n_checkpoints: int = 500,
    overwrite: bool = False,
):
    """Run cascade experiments by introducing dual line failures.

    Args:
        co2l (float): co2 level as float
        n_nodes (int): Number of nodes in PyPSA network.
        save_non_split_cascades (bool, optional): If False, only cascades that lead to system splits are saved. Defaults to True.
        check_n1_security (bool, optional): If 'True', check if the networks are n-1 secure before starting the dual line failure experiments.
        snet_index (int, optional): Select a particular subnetwork for calculations (if the pypsa network has different ones).
                For our data set, "0" indicates the Continental European AC grid. Defaults to 0.
        use_sclopf (bool): If 'True' use num_parallel lookup table for non sclopf PyPSA network and load this data set. Defaults to True.
        line_mitigation_dict (dict): Either 'None', which does not extend lines, or a dictionary that has information on how many lines to extend
        to mitigate the effect of dangerous system splits. Defaults to 'None'.
        stop_timestamp_str (str, optional): If not 'None', the simulation will stop at this timestamp. Defaults to None.
        n_checkpoints (int, optional): Number of save points to save the results. If negative, results are saved after every snapshot. Defaults to 500.
    """

    if use_sclopf:
        path_to_pypsa_network = path_to_pypsa_network_sclopf
        full_path_to_file = os.path.join(
            path_to_pypsa_network, 
            f"sclopf-elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-2920SEG.nc"
        )
    else:
        path_to_pypsa_network = path_to_pypsa_network_lopf
        full_path_to_file = os.path.join(
            path_to_pypsa_network, f"/elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-3H.nc"
        )

    if use_sclopf:
        save_path = save_path_sclopf
    else:
        save_path = save_path_lopf

    os.makedirs(save_path, exist_ok=True)

    fpath_out = os.path.join(save_path, 
                             f"/system_splits_Co2L{co2l}_n{n_nodes}")

    if not use_sclopf:
        fpath_out += "_lopf"

    if save_non_split_cascades:
        fpath_out += "_allcascades"

    if line_mitigation_dict is not None:
        fpath_out += f"_lineextension_nnlines{nn_links_extended}_deltanumpara{delta_num_parallel:.4g}"

    snapshots = data_handling.load_snapshot_list(co2lvl=co2l)
    snapshots = data_handling.load_snapshot_list(co2lvl=co2l)

    # If a start timestamp string was provided, snap it to the last available snapshot
    # that is not larger than the requested start_timestamp_str.
    if start_timestamp_str is not None or stop_timestamp_str is not None:
        # Ensure we have a sorted list of snapshot datetimes
        snapshots_list = sorted(list(snapshots))

    if start_timestamp_str is not None:
        target_dt = dt.strptime(start_timestamp_str, "%Y-%m-%d %H:%M")
        eligible = [s for s in snapshots_list if s <= target_dt]
        if eligible:
            snapped = eligible[-1]
            old = start_timestamp_str
            start_timestamp_str = snapped.strftime("%Y-%m-%d %H:%M")
            print(
                f"Adjusted start_timestamp_str from {old} to nearest snapshot {start_timestamp_str}"
            )
        else:
            # If no snapshot is <= target, use the first snapshot
            snapped = snapshots_list[0]
            start_timestamp_str = snapped.strftime("%Y-%m-%d %H:%M")
            print(
                f"Provided start_timestamp_str {target_dt} is earlier than first snapshot. "
                f"Using first snapshot {start_timestamp_str} as start."
            )

    # If a stop timestamp string was provided, snap it to the first available snapshot
    # that is not smaller than the requested stop_timestamp_str.
    if stop_timestamp_str is not None:
        target_dt = dt.strptime(stop_timestamp_str, "%Y-%m-%d %H:%M")
        # Ensure snapshots_list exists (handled above when either timestamp is provided)
        eligible = [s for s in snapshots_list if s >= target_dt]
        if eligible:
            snapped = eligible[0]
            old = stop_timestamp_str
            stop_timestamp_str = snapped.strftime("%Y-%m-%d %H:%M")
            print(
                f"Adjusted stop_timestamp_str from {old} to nearest snapshot {stop_timestamp_str}"
            )
        else:
            # If no snapshot is >= target, use the last snapshot
            snapped = snapshots_list[-1]
            stop_timestamp_str = snapped.strftime("%Y-%m-%d %H:%M")
            print(
                f"Provided stop_timestamp_str {target_dt} is later than last snapshot. "
                f"Using last snapshot {stop_timestamp_str} as stop."
            )
    if start_timestamp_str is not None:
        fpath_out += f"_from{start_timestamp_str.replace(' ', '_')}"

    if stop_timestamp_str is not None:
        fpath_out += f"_to{stop_timestamp_str.replace(' ', '_')}"

    if not overwrite and os.path.exists(fpath_out + ".pklz"):
        print(
            f"File {fpath_out + '.pklz'} already exists. Please remove it or set 'overwrite' to True."
        )
        return
    else:
        print(f"Running cascade simulations for {fpath_out}...")

    # network = data_handling.load_pypsa_network_from_path(full_path_to_file, use_sclopf)
    # nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)

    # Load PyPSA network, the graph of the subnetwork and its matrices
    nx_graph = data_handling.load_networkx_graph(snet_index=snet_index, co2lvl=co2l)
    injections_all_snapshots = data_handling.load_effective_injections(co2lvl=co2l)

    # Check if line extension mitigation is supposed to be run.
    # Networkx Graph is being modified, if line extension needs to be considered.
    if line_mitigation_dict is None:
        I_m, B_d, num_parallels, line_limits = data_handling.load_grid_matrices(
            snet_index=snet_index, co2lvl=co2l
        )

        # Calculate possible N-1 and N-2 failures (using non-bridges)
        bridge_idxs = data_handling.nx_edges_to_matrix_indices(
            nx.bridges(nx_graph), nx_graph
        )
        n_2_failures = cascade_simulation.calc_possible_double_line_failures(
            num_parallels, ignored_idxs=bridge_idxs, use_sclopf=use_sclopf
        )
        n_1_failures = cascade_simulation.calc_possible_single_line_failures(
            num_parallels, ignored_idxs=bridge_idxs
        )

    else:
        raise NotImplementedError(
            "Line extension mitigation not implemented yet."
        )  # this never really worked!

    if check_n1_security:
        ### Check N-1 stability ###
        print("\n#### N-1 failures: Co2 level", co2l, " | #Nodes:", n_nodes, " ####")
        for snapshot in tqdm(snapshots):
            if start_timestamp_str is not None:
                if dt.strptime(start_timestamp_str, "%Y-%m-%d %H:%M") > snapshot:
                    continue

            key_now = snapshot.strftime("%Y-%m-%d %H:%M")

            P_0 = injections_all_snapshots[snapshot]
            # P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

            for initial_failure in n_1_failures:

                failing_links, system_split = cascade_simulation.simulate_cascade(
                    I_m,
                    B_d,
                    P_0,
                    line_limits,
                    num_parallels,
                    initial_failure["failures"],
                    max_cascade_length=1,
                    use_sclopf=use_sclopf,
                )
                if len(failing_links) > 1:
                    raise (RuntimeError("PyPSA networks are not N-1 stable!"))
            if (
                stop_timestamp_str is not None
                and dt.strptime(stop_timestamp_str, "%Y-%m-%d %H:%M") <= snapshot
            ):
                break
    else:
        print("Warning: Not checking N-1 stability.")

    ### Simulation of N-2 failures ###
    print("\n#### N-2 failures: Co2 level", co2l, " | #Nodes:", n_nodes, " ####")
    splitting_cascades = dict()

    snapshots_within_bounds = snapshots
    if start_timestamp_str is not None:
        snapshots_within_bounds = snapshots_within_bounds[
            snapshots_within_bounds
            >= dt.strptime(start_timestamp_str, "%Y-%m-%d %H:%M")
        ]
    if stop_timestamp_str is not None:
        snapshots_within_bounds = snapshots_within_bounds[
            snapshots_within_bounds <= dt.strptime(stop_timestamp_str, "%Y-%m-%d %H:%M")
        ]
    if n_checkpoints == 0:
        checkpoint_snaphots = []
    else:
        if n_checkpoints < 0:
            n_checkpoints = len(snapshots)

        if n_checkpoints <= 0:
            checkpoint_idxs = np.array([], dtype=int)
        else:
            N = len(snapshots_within_bounds)
            # Need at least 3 snapshots to have interior points (exclude first and last)
            if N <= 2:
                checkpoint_idxs = np.array([], dtype=int)
            else:
                idxs = np.linspace(0, N, num=n_checkpoints + 2)[1:-1]
                checkpoint_idxs = np.unique(np.round(idxs).astype(int))
        checkpoint_snaphots = snapshots_within_bounds[checkpoint_idxs]
        print(f"Checkpoints will be created at {checkpoint_snaphots}.")
    last_checkpoint_snapshot = None

    for i, snapshot in enumerate(tqdm(snapshots_within_bounds)):
        key_now = snapshot.strftime("%Y-%m-%d %H:%M")

        if start_timestamp_str is not None:
            if dt.strptime(start_timestamp_str, "%Y-%m-%d %H:%M") > snapshot:
                continue

        if stop_timestamp_str is not None:
            print(f"running {key_now}, stop at {stop_timestamp_str}")
        # splitting_cascades[snapshot.strftime('%Y-%m-%d %H:%M')] = {}

        P_0 = injections_all_snapshots[snapshot]

        res_dict = dict()
        # for initial_failure in tqdm(n_2_failures, leave=False):
        for initial_failure in n_2_failures:
            failing_links, system_split = cascade_simulation.simulate_cascade(
                I_m,
                B_d,
                P_0,
                line_limits,
                num_parallels,
                initial_failure["failures"],
                use_sclopf=use_sclopf,
            )
            failures_tuple = tuple(initial_failure["failures"])

            if save_non_split_cascades:
                res_dict[failures_tuple] = (
                    failing_links,
                    system_split,
                    initial_failure["weight"],
                )
            elif system_split:
                res_dict[tuple(failures_tuple)] = (
                    failing_links,
                    initial_failure["weight"],
                )

        splitting_cascades[key_now] = res_dict

        if snapshot in checkpoint_snaphots:
            with gzip.open(
                fpath_out + "_checkpoint" + str(snapshot) + ".pklz", "wb"
            ) as handle:
                if line_mitigation_dict is None:
                    pickle.dump(
                        splitting_cascades, handle, protocol=pickle.HIGHEST_PROTOCOL
                    )
                else:
                    raise NotImplementedError(
                        "Line extension mitigation not implemented yet."
                    )
                    # pickle.dump(
                    #     (importance_all_lines, selected_edges, splitting_cascades),
                    #     handle,
                    #     protocol=pickle.HIGHEST_PROTOCOL,
                    # )
                if last_checkpoint_snapshot:
                    os.remove(fpath_out + "_checkpoint" + str(snapshot) + ".pklz")
                print(
                    f"######### Savepoint {i}, at snapshot {snapshot}. saved to",
                    fpath_out + "_checkpoint" + str(snapshot) + ".pklz #########",
                )
                last_checkpoint_snapshot = snapshot

        if (
            stop_timestamp_str is not None
            and dt.strptime(stop_timestamp_str, "%Y-%m-%d %H:%M") <= snapshot
        ):
            break

    with gzip.open(fpath_out + ".pklz", "wb") as handle:
        if line_mitigation_dict is None:
            pickle.dump(splitting_cascades, handle, protocol=pickle.HIGHEST_PROTOCOL)
        else:
            raise NotImplementedError("Line extension mitigation not implemented yet.")
            # pickle.dump(
            #     (importance_all_lines, selected_edges, splitting_cascades),
            #     handle,
            #     protocol=pickle.HIGHEST_PROTOCOL,
            # )
        print("saved to", fpath_out + ".pklz")

    if cfg.mattermost_url is not None:
        message_text = (
            "Cascade for dual line failures simulations (details in filename) with "
            + f"N={n_nodes}, C02_lvl={co2l} finished and results saved in '"
            + fpath_out
            + "'."
        )
        send_mattermost_messages.post_message(message_text, cfg.mattermost_url)

    return


def run_cascade_dual_line_failures_batch(
    batch_id: int,
    total_batches: int,
    co2l: float,
    n_nodes: int,
    start_date: str = "2013-01-01 00:00",
    end_date: str = "2013-12-31 23:00",
    **kwargs,
):
    """Run cascade dual line failures for a specific batch.

    Args:
        batch_id (int): Batch number (0-indexed)
        total_batches (int): Total number of batches
        co2l (float): CO2 level
        n_nodes (int): Number of nodes
        start_date (str): Overall start date for the simulation
        end_date (str): Overall end date for the simulation
        **kwargs: Additional arguments passed to run_cascade_dual_line_failures
    """
    from datetime import datetime, timedelta

    # Parse start and end dates
    start_dt = datetime.strptime(start_date, "%Y-%m-%d %H:%M")
    end_dt = datetime.strptime(end_date, "%Y-%m-%d %H:%M")

    # Calculate total duration and batch duration
    total_duration = end_dt - start_dt
    batch_duration = total_duration / total_batches

    # Calculate this batch's start and end times
    batch_start = start_dt + batch_id * batch_duration
    batch_end = start_dt + (batch_id + 1) * batch_duration

    # Format as strings (matching the expected format)
    start_timestamp_str = batch_start.strftime("%Y-%m-%d %H:%M")
    end_timestamp_str = batch_end.strftime("%Y-%m-%d %H:%M")

    print(
        f"Batch {batch_id}: Running from {start_timestamp_str} to {end_timestamp_str}"
    )

    # Call the main function with calculated timestamps
    return run_cascade_dual_line_failures(
        co2l=co2l,
        n_nodes=n_nodes,
        start_timestamp_str=start_timestamp_str,
        stop_timestamp_str=end_timestamp_str,
        **kwargs,
    )


def collect_batch_results(
    path_to_results: str,
    co2l: float,
    n_nodes: int,
    required_str: list = [],
    exclude_str: list = [],
    save_dir: str = None,
    all_cascades: bool = True,
):
    """Collect batch results based on required strings in filenames.

    Args:
        required_str (list(str)): List of strings that must be in the
        filenames to include the batch results.
        exclude_str (list(str)): List of strings that must not be in the
        filenames to include the batch results.

    Returns:
        dict: A dictionary with batch IDs as keys and their results as values.
    """
    batch_files = []
    collected_results = {}
    collected_results_splitting = {}

    candidate_files = os.listdir(path_to_results)
    print(f"Scanning {len(candidate_files)} files in {path_to_results}. Filtering....")

    splitting_cascades_save_path = os.path.join(
        save_dir, f"/system_splits_Co2L{co2l}_n{n_nodes}.pklz"
    )
    if all_cascades and save_dir is not None:
        all_cascades_save_path = os.path.join(
            save_dir, f"system_splits_Co2L{co2l}_n{n_nodes}_allcascades.pklz"
        )

    if os.path.exists(splitting_cascades_save_path):
        print("Collected results file already exists at:", splitting_cascades_save_path)
        return

    required_str += [f"Co2L{co2l}", f"n{n_nodes}"]
    for filename in tqdm(candidate_files):
        if not filename.endswith(".pklz"):
            continue
        if any(req not in filename for req in required_str):
            continue
        if any(exc in filename for exc in exclude_str):
            continue
        batch_files.append(filename)

    batch_files.sort()

    print(f"Found {len(batch_files)} batch files matching criteria. Concatenating...")

    for filename in tqdm(batch_files, desc=f"Collecting batch results of co2l {co2l}"):
        with gzip.open(os.path.join(path_to_results, filename), "rb") as handle:
            result = pickle.load(handle)
        if all_cascades:
            collected_results.update(result)

        for timestamp, failure_to_cascades in tqdm(result.items(), leave=False):
            if timestamp not in collected_results_splitting.keys():
                collected_results_splitting[timestamp] = {}
            for failure, (
                cascades,
                system_split,
                weight,
            ) in failure_to_cascades.items():
                if system_split:
                    collected_results_splitting[timestamp][failure] = (
                        cascades,
                        weight,
                    )

    print(f"{len(collected_results)} snapshots collected from batch results.")

    if save_dir is not None:
        os.makedirs(save_dir, exist_ok=True)
        with gzip.open(splitting_cascades_save_path, "wb") as handle:
            pickle.dump(
                collected_results_splitting, handle, protocol=pickle.HIGHEST_PROTOCOL
            )
        print(f"Collected results saved to: {save_dir}")

    if all_cascades and save_dir is not None:
        with gzip.open(
            all_cascades_save_path,
            "wb",
        ) as handle:
            pickle.dump(collected_results, handle, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"All cascades results saved to: {save_dir}")

    return collected_results


def verify_collected_results(
    collected_filepath: str,
    expected_start_date: str = "2013-01-01 00:00",
    expected_end_date: str = "2013-12-31 23:00",
):
    """Verify that collected results cover the expected time range.

    Args:
        collected_filepath (str): Path to collected results file
        expected_start_date (str): Expected start date
        expected_end_date (str): Expected end date
    """
    from datetime import datetime

    print(f"Verifying collected results in: {collected_filepath}")

    # Load collected results
    with gzip.open(collected_filepath, "rb") as handle:
        data = pickle.load(handle)

    # Handle different data structures
    if isinstance(data, tuple):
        # With line mitigation: (importance_all_lines, selected_edges, splitting_cascades)
        splitting_cascades = data[2]
    else:
        # Without line mitigation: splitting_cascades dict
        splitting_cascades = data

    # Get timestamps from results
    timestamps = list(splitting_cascades.keys())
    timestamps_dt = [datetime.strptime(ts, "%Y-%m-%d %H:%M") for ts in timestamps]
    timestamps_dt.sort()

    # Expected range
    expected_start = datetime.strptime(expected_start_date, "%Y-%m-%d %H:%M")
    expected_end = datetime.strptime(expected_end_date, "%Y-%m-%d %H:%M")

    # Verification
    actual_start = min(timestamps_dt)
    actual_end = max(timestamps_dt)

    print(f"Expected time range: {expected_start} to {expected_end}")
    print(f"Actual time range: {actual_start} to {actual_end}")
    print(f"Total timestamps: {len(timestamps)}")

    # Check for gaps (assuming hourly data)
    snapshots = 2920
    print(f"Expected number of hourly timestamps: {snapshots}")

    if len(timestamps) == snapshots:
        print("✓ Complete time coverage")
    else:
        print(f"⚠ Missing {snapshots - len(timestamps)} timestamps")

    # Check for duplicates
    if len(timestamps) == len(set(timestamps)):
        print("✓ No duplicate timestamps")
    else:
        print(f"⚠ {len(timestamps) - len(set(timestamps))} duplicate timestamps found")

    return {
        "total_timestamps": len(timestamps),
        "expected_timestamps": snapshots,
        "actual_start": actual_start,
        "actual_end": actual_end,
        "has_duplicates": len(timestamps) != len(set(timestamps)),
    }


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Cluster blackouts")
    
    parser.add_argument(
        "--co2l", nargs="+", type=float, help="CO2 levels to cluster", default=None
    )
    
    parser.add_argument(
        "--no_check_n1", action="store_true", help="Don't check n-1 stability", default=False
    )
    

    args = parser.parse_args()

    n_nodes = 600
    
    check_n_1 = not args.no_check_n1
    
    if args.co2l is not None:
        co2ls = args.co2l
    else:
        co2ls = list(get_co2_levels(n_nodes))
        
    # Load arguments
    n_nodes = 600
    co2ls = get_co2_levels(n_nodes)
    if isinstance(co2ls, float):
        co2ls = [co2ls]
    
    save_whole_cascades = False  # set this to true if you want to save all cascades, 
    # not only the ones that lead to system splits. Be aware that this can lead to very large files, 
    # especially for lower CO2 levels where many cascades are triggered.

    for co2l in co2ls:
        run_cascade_dual_line_failures(
            co2l,
            n_nodes,
            save_non_split_cascades=save_whole_cascades,
            use_sclopf=True,
            n_checkpoints=10,
            check_n1_security=check_n_1,
            overwrite=True,
        )

    ### Cascades can also be run in batches to speed up the computation by parallelization.
    # co2l=0.6
    # total_batches = 2
    # for batch_id in range(total_batches):
    #     output_filename = run_cascade_dual_line_failures_batch(
    #         batch_id=batch_id,
    #         total_batches=total_batches,
    #         co2l=co2l,
    #         n_nodes=600,
    #         save_whole_cascades=True,
    #         use_sclopf=True,
    #         check_n1_security=False,
    #         overwrite=True,
    #         n_checkpoints=2,
    #     )

    # output_filename = f"system_splits_Co2L{co2l}_n{n_nodes}"

    # if not use_sclopf:
    #     output_filename += "_lopf"

    # if save_whole_cascades:
    #     output_filename += "_allcascades"

    # if start_date is not None:
    #     output_filename += f"_from{start_date.replace(' ', '_')}"

    # if end_date is not None:
    #     output_filename += f"_to{end_date.replace(' ', '_')}"
    # output_filename = output_filename + "_collected.pklz"

    # collect_batch_results(
    #     co2l=co2l,
    #     n_nodes=600,
    #     total_batches=total_batches,
    #     start_date=start_date,
    #     end_date=end_date,
    #     use_sclopf=True,
    #     save_whole_cascades=True,
    #     output_filename=output_filename,
    #     cleanup_batch_files=False,
    # )
    # verify_collected_results(
    #     collected_filepath=save_path_sclopf + output_filename,
    #     expected_start_date=start_date,
    #     expected_end_date=end_date,
    # )
