#!/usr/bin/env python
# -*- coding: utf-8 -*

"""Run cascade experiments by introducing line failures
to the optimal power systems generated by PyPSA."""

import gzip
import os
import pickle
import sys
from datetime import datetime as dt

import networkx as nx
import pandas as pd
from tqdm import tqdm

sys.path.append("./")
# Send messages to mattermost
import utils.config as cfg
from utils import (
    cascade_simulation,
    data_handling,
    extend_transmission_capacity,
    send_mattermost_messages,
)
from utils.config import (
    path_to_cascade_results_lopf,
    path_to_cascade_results_sclopf,
    path_to_pypsa_network_lopf,
    path_to_pypsa_network_sclopf,
)

# Setup paths to solved PyPSA networks and results of this script
save_path_lopf = path_to_cascade_results_lopf
save_path_sclopf = path_to_cascade_results_sclopf

# Dummy decorator to not get stuck on @profile if not using profiling
if "profile" not in globals():

    def profile(func):
        return func


def run_cascade_single_line_failures(
    co2l: float,
    n_nodes: int,
    epsilon: float = 1e-4,
    save_whole_cascades: bool = False,
    snet_index: int = 0,
    use_sclopf: bool = False,
    initial_remove_all: bool = False,
):
    """Run the cascade simulation for single line failures.

    Args:
        co2l (float): CO2 level of the previously simulated PyPSA networks.
        n_nodes (int): Number of nodes fo the PyPSA networks.
        epsilon (float): Limit above smax needed for a line to fail. Default 1e-4.
        save_all_cascades (bool, optional): If False, only the cascade trigger is saved. Defaults to False.
        snet_index (int, optional): _description_. Defaults to 0.
        use_sclopf (bool): If 'True' use num_parallel lookup table for non sclopf PyPSA network and load this data set. Defaults to False.
        initial_remove_all (bool): If 'True' remove all initial circuits and not use look_up_table.
    """

    # Load PyPSA network, the graph of the subnetwork and its matrices
    if use_sclopf:
        path_to_pypsa_network = path_to_pypsa_network_sclopf
        full_path_to_file = (
            path_to_pypsa_network
            + f"sclopf-elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l:.1f}-2920SEG.nc"
        )
    else:
        path_to_pypsa_network = path_to_pypsa_network_lopf
        full_path_to_file = (
            path_to_pypsa_network + f"elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-3H.nc"
        )

    network = data_handling.load_pypsa_network_from_path(full_path_to_file, use_sclopf)
    nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)
    I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(
        nx_graph
    )

    # Calculate possible N-1 failures (using non-bridges)
    bridge_idxs = data_handling.nx_edges_to_matrix_indices(
        nx.bridges(nx_graph), nx_graph
    )
    n_1_failures = cascade_simulation.calc_possible_single_line_failures(
        num_parallels, ignored_idxs=bridge_idxs
    )

    splitting_cascades = dict()

    for snapshot in tqdm(network.snapshots):
        key_now = snapshot.strftime("%Y-%m-%d %H:00")
        P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

        res_dict = dict()
        for initial_failure in n_1_failures:

            failing_links, system_split = cascade_simulation.simulate_cascade(
                I_m,
                B_d,
                P_0,
                line_limits,
                num_parallels,
                initial_failure,
                use_sclopf=use_sclopf,
                epsilon=epsilon,
                initial_remove_all=initial_remove_all,
            )
            if use_sclopf and len(failing_links) > 1:
                raise RuntimeError("PyPSA networks are not N-1 stable!")

            if save_whole_cascades:
                res_dict[tuple(initial_failure)] = failing_links, system_split

            elif system_split:
                res_dict[tuple(initial_failure)] = failing_links

        splitting_cascades[key_now] = res_dict

    if use_sclopf:
        save_path = save_path_sclopf
    else:
        save_path = save_path_lopf
    os.makedirs(save_path, exist_ok=True)

    fpath_out = save_path + f"system_splits_singlelinefailures_Co2L{co2l}_n{n_nodes}"

    if abs(epsilon - 1e-4) > 1e-8:
        fpath_out += f"_epsilon{epsilon:.4e}"

    if not use_sclopf:
        fpath_out += "_lopf"

    if save_whole_cascades:
        fpath_out += "_allcascades"

    if initial_remove_all:
        fpath_out += "_allinitialcircuits"

    with gzip.open(fpath_out + ".pklz", "wb") as handle:
        pickle.dump(splitting_cascades, handle, protocol=pickle.HIGHEST_PROTOCOL)

    if cfg.mattermost_url is not None:
        message_text = (
            "Cascade for single line failures simulations (details in filename)"
            + f"with N={n_nodes}, C02_lvl={co2l} finished and results saved in '"
            + fpath_out
            + "'."
        )
        send_mattermost_messages.post_message(message_text, cfg.mattermost_url)

    return


@profile
def run_cascade_dual_line_failures(
    co2l: float,
    n_nodes: int,
    save_all_cascades: bool = False,
    snet_index: int = 0,
    check_n1_security: bool = True,
    use_sclopf: bool = True,
    line_mitigation_dict: dict = None,
    stop_timestamp_str: str = None,
):
    """Run cascade experiments by introducing dual line failures.

    Args:
        co2l (float): co2 level as float
        n_nodes (int): Number of nodes in PyPSA network.
        save_all_cascades (bool, optional): _description_. Defaults to False.
        check_n1_security (bool, optional): If 'True', check if the networks are n-1 secure before starting the dual line failure experiments.
        snet_index (int, optional): Select a particular subnetwork for calculations (if the pypsa network has different ones).
                For our data set, "0" indicates the Continental European AC grid. Defaults to 0.
        use_sclopf (bool): If 'True' use num_parallel lookup table for non sclopf PyPSA network and load this data set. Defaults to True.
        line_mitigation_dict (dict): Either 'None', which does not extend lines, or a dictionary that has information on how many lines to extend
        to mitigate the effect of dangerous system splits. Defaults to 'None'.
    """

    if use_sclopf:
        path_to_pypsa_network = path_to_pypsa_network_sclopf
        full_path_to_file = (
            path_to_pypsa_network
            + f"sclopf-elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l:.1f}-2920SEG.nc"
        )
    else:
        path_to_pypsa_network = path_to_pypsa_network_lopf
        full_path_to_file = (
            path_to_pypsa_network + f"elec_s_{n_nodes}_ec_lv1.0_Co2L{co2l}-3H.nc"
        )

    if use_sclopf:
        save_path = save_path_sclopf
    else:
        save_path = save_path_lopf

    fpath_out = save_path + f"system_splits_Co2L{co2l}_n{n_nodes}"

    if not use_sclopf:
        fpath_out += "_lopf"

    # Load PyPSA network, the graph of the subnetwork and its matrices
    network = data_handling.load_pypsa_network_from_path(full_path_to_file, use_sclopf)
    nx_graph = data_handling.build_networkx_graph(network, snet_index=snet_index)

    # Check if line extension mitigation is supposed to be run.
    # Networkx Graph is being modified, if line extension needs to be considered.
    if line_mitigation_dict is None:
        I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(
            nx_graph
        )

        # Calculate possible N-1 and N-2 failures (using non-bridges)
        bridge_idxs = data_handling.nx_edges_to_matrix_indices(
            nx.bridges(nx_graph), nx_graph
        )
        n_2_failures = cascade_simulation.calc_possible_double_line_failures(
            num_parallels, ignored_idxs=bridge_idxs, use_sclopf=use_sclopf
        )
        n_1_failures = cascade_simulation.calc_possible_single_line_failures(
            num_parallels, ignored_idxs=bridge_idxs
        )

    else:
        # Cascade simulation with extended lines
        nn_links_extended = line_mitigation_dict["nn_links"]
        delta_num_parallel = line_mitigation_dict["delta_num_parallel"]
        extension_type = line_mitigation_dict["extension_type"]
        casc_dict = None

        if extension_type == "most_likely_primary":

            # Load previously generated cascade results
            with gzip.open(fpath_out + ".pklz", "rb") as fh_in:
                casc_dict = pickle.load(fh_in)

            # Check if all times have a cascade entry
            set_diff_len = len(
                set(network.snapshots) - set(pd.to_datetime(list(casc_dict.keys())))
            )
            assert (
                set_diff_len == 0
            ), f"Cascade dict does not have same entries but {set_diff_len} different ones!"

            print(
                "\n## Running for line extension: Loading previously found cascade dictionary!\n"
                + " First, likelihoods of primary and secondary failures are being evaluated:"
            )
        nx_graph_mod, importance_all_lines, selected_edges = (
            extend_transmission_capacity.increase_capacity_most_important_lines(
                network,
                nx_graph,
                nn_links_extended,
                delta_num_parallel,
                co2l,
                casc_dict=casc_dict,
                extension_type="most_impactful_primary",
            )
        )

        # Check if the lines have been correctly extend
        assert len(selected_edges) == nn_links_extended
        assert all(
            [
                abs(
                    (
                        nx_graph_mod.edges[xx]["num_parallel"]
                        - nx_graph.edges[xx]["num_parallel"]
                    )
                    - delta_num_parallel
                )
                < 1e-8
                for xx in selected_edges
            ]
        )
        assert all(
            [
                abs(
                    nx_graph_mod.edges[xx]["num_parallel"]
                    - nx_graph.edges[xx]["num_parallel"]
                )
                < 1e-8
                for xx in nx_graph.edges
                if xx not in selected_edges
            ]
        )
        assert len(selected_edges) == nn_links_extended
        assert all(
            [
                abs(
                    (
                        nx_graph_mod.edges[xx]["s_nom"] / nx_graph.edges[xx]["s_nom"]
                        - nx_graph_mod.edges[xx]["num_parallel"]
                        / nx_graph.edges[xx]["num_parallel"]
                    )
                )
                < 1e-8
                for xx in selected_edges
            ]
        )
        assert all(
            [
                abs(nx_graph_mod.edges[xx]["s_nom"] - nx_graph.edges[xx]["s_nom"])
                < 1e-8
                for xx in nx_graph.edges
                if xx not in selected_edges
            ]
        )

        # Overwrite graph with modified graph
        I_m, B_d, num_parallels, line_limits = data_handling.get_matrices_from_nx_graph(
            nx_graph_mod
        )
        nx_graph = nx_graph_mod

        # Calculate possible N-1 and N-2 failures (using non-bridges)
        bridge_idxs = data_handling.nx_edges_to_matrix_indices(
            nx.bridges(nx_graph), nx_graph
        )
        n_2_failures = cascade_simulation.calc_possible_double_line_failures(
            num_parallels, ignored_idxs=bridge_idxs, use_sclopf=use_sclopf
        )
        n_1_failures = cascade_simulation.calc_possible_single_line_failures(
            num_parallels, ignored_idxs=bridge_idxs
        )

    if check_n1_security:
        ### Check N-1 stability ###
        print("\n#### N-1 failures: Co2 level", co2l, " | #Nodes:", n_nodes, " ####")
        for snapshot in tqdm(network.snapshots):

            key_now = snapshot.strftime("%Y-%m-%d %H:00")

            P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

            for initial_failure in n_1_failures:

                failing_links, system_split = cascade_simulation.simulate_cascade(
                    I_m,
                    B_d,
                    P_0,
                    line_limits,
                    num_parallels,
                    initial_failure,
                    max_cascade_length=1,
                    use_sclopf=use_sclopf,
                )
                if len(failing_links) > 1:
                    raise (RuntimeError("PyPSA networks are not N-1 stable!"))
            if (
                stop_timestamp_str is not None
                and dt.strptime(stop_timestamp_str, "%Y-%m-%d %H:00") <= snapshot
            ):
                break

    ### Simulation of N-2 failures ###
    print("\n#### N-2 failures: Co2 level", co2l, " | #Nodes:", n_nodes, " ####")
    splitting_cascades = dict()
    for snapshot in tqdm(network.snapshots):
        key_now = snapshot.strftime("%Y-%m-%d %H:00")

        if stop_timestamp_str is not None:
            print(f"running {key_now}, stop at {stop_timestamp_str}")
        # splitting_cascades[snapshot.strftime('%Y-%m-%d %H:00')] = {}

        P_0 = data_handling.get_effective_injections(network, snapshot, nx_graph)

        res_dict = dict()
        for initial_failure in tqdm(n_2_failures, leave=False):

            failing_links, system_split = cascade_simulation.simulate_cascade(
                I_m,
                B_d,
                P_0,
                line_limits,
                num_parallels,
                initial_failure,
                use_sclopf=use_sclopf,
            )

            if save_all_cascades:
                # splitting_cascades[snapshot.strftime('%Y-%m-%d %H:00')][tuple(initial_failure)] = failing_links
                res_dict[tuple(initial_failure)] = failing_links, system_split

            elif system_split:
                # splitting_cascades[snapshot.strftime('%Y-%m-%d %H:00')][tuple(initial_failure)] = failing_links
                res_dict[tuple(initial_failure)] = failing_links

        splitting_cascades[key_now] = res_dict

        if (
            stop_timestamp_str is not None
            and dt.strptime(stop_timestamp_str, "%Y-%m-%d %H:00") <= snapshot
        ):
            break

    if save_all_cascades:
        fpath_out += "_allcascades"

    if line_mitigation_dict is not None:
        fpath_out += f"_lineextension_nnlines{nn_links_extended}_deltanumpara{delta_num_parallel:.4g}"

    if stop_timestamp_str is not None:
        fpath_out += f"_stopped_{stop_timestamp_str}"

    with gzip.open(fpath_out + ".pklz", "wb") as handle:
        if line_mitigation_dict is None:
            pickle.dump(splitting_cascades, handle, protocol=pickle.HIGHEST_PROTOCOL)
        else:
            pickle.dump(
                (importance_all_lines, selected_edges, splitting_cascades),
                handle,
                protocol=pickle.HIGHEST_PROTOCOL,
            )
        print("saved to", fpath_out + ".pklz")

    if cfg.mattermost_url is not None:
        message_text = (
            "Cascade for dual line failures simulations (details in filename) with "
            + f"N={n_nodes}, C02_lvl={co2l} finished and results saved in '"
            + fpath_out
            + "'."
        )
        send_mattermost_messages.post_message(message_text, cfg.mattermost_url)

    return


if __name__ == "__main__":

    # Load arguments
    co2l_in = float(sys.argv[1])
    n_nodes_in = int(sys.argv[2])
    # stop_timestamp_str = "2013-01-01 04:00:00"
    if len(sys.argv) > 3:
        save_all_cascades_in = bool(sys.argv[3])
    else:
        save_all_cascades_in = False
    print("Starting single line failures")
    run_cascade_single_line_failures(
        co2l_in,
        n_nodes_in,
        save_whole_cascades=save_all_cascades_in,
        use_sclopf=False,
        # check_n1_security=False,
        # line_mitigation_dict=None,
    )
